.gitignore
anesthetic/gui/plot.py
anesthetic/plot.py
anesthetic/samples.py
anesthetic/utils.py
setup.py

Provides part of the enhancement for #2 "Option for histograms as alternative to KDE".
* Appended `.gitignore`
* Created function `hist_1d()` in plot.py to be called instead of the KDE plot from the function `plot_1d()`.
- Uses (optionally) astropy's `hist` function which has the same functionality as matplotlib's own hist function with the extension of moresophisticated algorithms for determining bins. The bins keyword e.g. can be set to 'knuth' (default) or 'blocks' (even better but less reliable). Reverts to matplotlib's `hist` if astropy is not installed.
- The histograms are renormalised such that the highest bar has a height of unity. This simplifies the choice of y-limits and since the y-axis isn't labelled in the diagonal 1D plots of the triangle plots, the absolute height isn't …

Option of using 1D histograms instead of KDE plots

---

anesthetic/plot.py
tests/test_plot.py

* Change `ax.plot` to `ax.scatter` in `scatter_plot_2d` in plot.py
- This is more true to the intention of the plots and provides the
additional functionalities of a scatter plot (could be expanded to
make so-to-speak '3D' plots using a colormap).
- Change default markersize to s=3 as the matplotlib default is
typically too large for the amount of points we are dealing with
here.
- Documentation adapted accordingly.
Changes to be committed:
* modified:   anesthetic/plot.py

change plot to scatter for 2D scatter plot option

---

tests/matplotlib_agg.py
tests/test_gui.py
tests/test_plot.py
tests/test_samples.py

Using `matplotlib.pyplot` when running pytest will throw 
```python
ImportError: No module named Tkinter
```
for many people (particularly people using jupyter notebooks?). All this requires to fix it is to put the lines
```python
import matplotlib
matplotlib.use('Agg')
```
at the head of the `test/test*.py` files.

set matplotlib.use('Agg') in test*.py files to avoide ImportError for Tkinter

---

.coveragerc
.travis.yml
run_tests

The build matrix is large, and testing times are now getting quite long. It
would be nice if we didn't burn a lot of unecessary time installing via pip
over and over again

Pip caching and parallelisation to speed up travis builds

---

anesthetic/samples.py

In #21 the calls of `ax.plot([], [])` and similar were changed to setting `x = []` and passing it to the plotting functions. This does not take care of the different colour cycles of plot and scatter and thus does not work. 
Thus, here I am reverting some of the changes from #21. 
It might be good to write a test for this where it actually checks the colours used. This might be much easier once #30 is merged.
Fixes #31

Fix colorcycle

---

anesthetic/plot.py
anesthetic/samples.py
demo.ipynb
demo.py
tests/test_samples.py

Legend handling is now more intuitive, i.e. can be done in the usual matplotlib fashion.
* Make the link `axes[x][x] = axes[x][x].twin` such that the user has direct access to the diagonal axes that have actually been drawn in.
- `axes[x][x].legend()` now automatically makes a legend in the diagonal axes.
* Create the legend proxy already in `contour_plot_2d` and pass it to `ax.patches`.
- `axes[x][y].legend()` now automatically makes a legend in the 2D 'kde' axes.
- No need for `get_legend_proxy` anymore, because matplotlib's own functions can handle this, now:
```python
handles, labels = axes[x][y].get_legend_handles_labels()
leg = fig.legend(handles, labels)
```
- Flagged `get_legend_proxy` as deprecated.

Make legend handling more intuitive and consistent with `matplotlib`

---

anesthetic/plot.py
tests/test_plot.py

As noted in #25, triangle plots were not linking the x and y axes limits of subplots with the same parameter.
This pull request implements this with a single function and a bit of python function magic.
It even works with ipython inline plot resizing

Linking of x and y axis limits in triangle plots

---

anesthetic/samples.py
tests/test_samples.py

Added a `label` attribute to `MCMCSamples`, which provides a default for the plots. Labels are defined to be the basename of the root if loaded from file, None otherwise.
Fixes #42

Automatic labelling

---

anesthetic/samples.py
tests/test_samples.py

This PR added a failing test that shows the issue noted in #19. It now fixes that test by reordering the 'blank plots' in `MCMCSamples.plot`
Fixes #19

Fix to colouring for missing plots

---

anesthetic/boundary.py
anesthetic/plot.py

This implements a 'cut and normalise' boundary correction. Whilst [far better corrections are available](https://cosmologist.info/notes/GetDist.pdf), this is manifestly better than no correction, and has the advantage of being an extremely minor modification.
The below plots show that it slightly improves x2 and x4, and clearly improves x3.
Without boundary correction:
With boundary correction:
Fixes #35

First-order boundary correction

---

.travis.yml
README.rst
anesthetic/samples.py
anesthetic/utils.py
anesthetic/weighted_pandas.py
tests/test_samples.py
tests/test_weighted_pandas.py

This fixes #53 by ensuring that the invisible weights array is sliced whenever the array is.

Weighted dataframe slicing

---

anesthetic/samples.py
tests/test_samples.py

This allows column names to be passed manually to both `MCMCSamples` and `NestedSamples` but behaves as usual if only the root is passed.
Addresses #37 and #38.

Add columns kwarg

---

README.rst
anesthetic/plot.py
anesthetic/utils.py
tests/test_plot.py

Recently I've been using the 2d-histogram plotting, and found a couple of bugs:
- When plotting with samples drawn from a wide range but with low weight (i.e. a typical nested sampling run), the axes resized in a way that was annoying, and iconsistent with the way that ``plot_hist_1d works``. This PR fixes this, and supplies a test that fails with the old code, but passes with the update
- There is a 'non-zero edge' correction in `iso_probability_contours` that apparently doesn't do anything except break in certain difficult to define cases. Removing it makes it more consistent with the behaviour of `iso_probability_contours_from_samples` and does not break. Will reinstate this code if it does become clear that it was serving a specific purpose.
Fixes # (issue)

Bug fix for histogram plotting

---

README.rst
anesthetic/samples.py
tests/example_data/pc.ranges
tests/test_samples.py

Automatically set all limits not specified by a `.ranges` file to their respective minimum and maximum values in the sample.
Fixes #36

automatic minmax limits

---

anesthetic/samples.py
tests/test_samples.py

Implements minimal change suggested in #84 .
Fixes #84

-infinity handling in set_beta

---

anesthetic/boundary.py
anesthetic/gui/plot.py
anesthetic/kde.py
anesthetic/plot.py
anesthetic/read/getdistreader.py
anesthetic/read/montepythonreader.py
anesthetic/read/multinestreader.py
anesthetic/read/polychordreader.py
anesthetic/samples.py
anesthetic/utils.py
anesthetic/weighted_pandas.py
bin/gen_data.py
bin/plot.py
images/animate.py
tests/test_plot.py
tests/test_samples.py
tests/test_utils.py
tests/test_weighted_pandas.py

Following #76, this replaces all instances of `numpy` with `np`.
This obviously shortens some lines of code, meaning that they no longer needed to be broken over lines. I took this opportunity to do so where possible whilst remaining PEP8 compliant.
I made one minor change to a test which previously used `pdarray[column][index]`. It is more future-proof to use `pdarray.loc[index, column]`, since this will give a modifiable view onto an array in future versions of pandas, whilst the other will not (and was currently raising a warning)
Fixes #76

Convert numpy to np

---

README.rst
anesthetic/plot.py

There are some plotting kwargs that are currently not user accessible such as the kwarg `range` for 1d histograms. That kwarg is important when faced with a big dynamic range in values such as for `logL` where only a small range is typically relevant for plotting though, which the user should be able to restrict.
More generally, I think we should try to keep as many kwargs passed to `plt.plot`, `plt.hist`, `plt.contour` etc. user accessible as possible. For most kwargs that is already the case, but a few have slipped us by.

make plotting kwargs user accessible

---

anesthetic/read/getdistreader.py
anesthetic/read/samplereader.py
anesthetic/samples.py
tests/test_samples.py

* Provides functionality to read MCMC chains from Cobaya which use `.` instead of `_` for their chains and which have a `.yaml` file instead of a `.paramnames` file.
* Provides functionality to discard burn-in samples, which is useful e.g. when comparing PolyChord results to Planck MCMC chains.
Fixes #18

Read cobaya mcmc

---

anesthetic/convert.py
demo.ipynb
demo.py
requirements_extras.txt
tests/test_convert.py

This is code which anecdotally I know would be useful to other users who have large plotting pipelines in getdist, but would like to be able to make use of anesthetics nested sampling post-processing tools.

Added code for a getdist converter

---

README.rst
anesthetic/plot.py
tests/test_samples.py

This PR starts a fix for #96, by pushing a failing test, which will be fixed by masking out zero weights in the covariance matrix calculation.
Fixes #96

Nan - zero weight bug fix for contour plot covariance computation

---

anesthetic/samples.py
anesthetic/weighted_pandas.py
tests/test_samples.py
tests/test_weighted_pandas.py

This addresses all the points in #91, aside from `logL_birth`, which like `logL` is overriden by `root`, so there is no 'default' per-se. If root is not supplied, then you should supply a `logL_birth` of some form, although this cannot be an error if not on account of how it extends the underlying `pd.DataFrame` class.
Fixes #91

Added missing default values to NestedSamples

---

README.rst
requirements.txt

scipy's `gaussian_kde` only accepts the kwarg `weights` from version `1.2.0` onwards. Update anesthetic requirements accordingly.
Fixes #106

add minimum scipy version

---

anesthetic/samples.py
tests/test_samples.py

This PR cleans up the xmin and xmax interface by allowing users to override xmin and xmax as user-provided kwargs (which also reduces the length of the code).
Fixes #89 by returning no limits `(None, None)` if equal limits are specified for any reason.
Initial test fails for first commit, which is fixed by the second.

Equal min and max limits fix

---

anesthetic/plot.py
tests/test_plot.py

The quantile kwarg `q` introduced in #99 causes warnings and errors in the 2d plots for fastkde, kde, and scatter.
This PR removes it (`kwargs.pop('q', None)`) before calling the plotting functions.

Pop quantile kwarg q in 2d

---

anesthetic/weighted_pandas.py
tests/test_weighted_pandas.py

Make a change similar to #102 for statistical functions (mean, var, etc.) in `WeightedSeries` and `WeightedDataFrame` to better handle `nan` in the data.
Fixes #111

add tests for nan in data with zero weights causing issues in mean, var, std, cov

---

README.rst
anesthetic/plot.py

Eagle-eyed anesthetic users will have noted that sometimes there is a small shaded rectangle in the lower left corner of a contour plot canvas. This is caused by the patches that are appended to contour plots in order to generate a pleasing legend icon. The small rectangle can be removed by adjusting the patch to be zero size. This is a very minor bug fix, so should not require any additional tests.
Note that since the recent release of matplotlib 3.3, a couple of the tests now fail due to a change in the behaviour of gridspec. This PR also addresses this by checking before attempting to construct a zero sized grid of plots.

Bug fix for contour plots

---

README.rst
requirements.txt
requirements_extras.txt
setup.py

Following #115  which notes that master is now broken on account of the pandas update to 1.1, this PR freezes to pandas to 1.0.5 until #115 is resolved

Freezing pandas at 1.0.5

---

README.rst
anesthetic/plot.py
anesthetic/utils.py
demo.ipynb
demo.py
tests/test_plot.py

Been wanting the option to create unfilled contours for  a while. Particularly useful when faced with slim contours such as for inflation models in an ns-r-plot, which basically only consist of contour lines and thus all appear black. 
Also, if `cmap` is provided instead of `color`, then `color` is set to the colour of the inner contours for line plots or scatter plots.

Unfilled contours and inherit color from cmap

---

anesthetic/samples.py
anesthetic/utils.py
tests/test_samples.py
tests/test_utils.py

This pull request implements some of the code that underpins https://arxiv.org/abs/2006.03371 
@andrewfowlie will likely have an opinion on which other pieces of code from
that paper are sufficiently general to make it into this paper

Added code to compute insertion indices

---

tests/test_samples.py

This introduces 2 tests:
1) Apply a logzero mask at the prior level (i.e. _discard_ samples completely). 
2) Apply a logzero mask at the likelihood level (i.e. set `logL` to `-inf`).
Both tests take two approaches each and compare those internally. 
The **first** approach applies the mask to the samples directly and 1) discards them or 2) sets the corresponding `logL` to `-inf` and then recomputes `ns_output()`. 
The **second** approach applies the mask to the weights and computes 1) prior and posterior volume change or 2) only posterior volume change to then infer the new log evidence.
This PR was suggested in #119 to see whether changes there affect the comparison here.
---
```python
ns0 = NestedSamples(root="/home/hergtl/Documents/Projects/AnestheticPrj/anesthetic/tests/example_data/pc" …
```

logzero masking at prior and likelihood level

---

anesthetic/samples.py
tests/test_samples.py

- Added `NestedSamples.prior_points()` as alias for `NestedSamples.posterior_points(0)`.
- Added `NestedSamples.convert_to_prior()` as alias for `NestedSamples.set_beta(0)`. (Not sure if `NestedSamples.prior()` would be a better name).
Fixes #118

Added prior and prior_points shortcuts

---

anesthetic/samples.py
tests/test_samples.py

As mentioned in #133, `MCMCSamples.importance_sample` is not adjusting the weights (which it should).
Fixes #133

fix `MCMCSamples.importance_sample`

---

README.rst
anesthetic/kde.py
anesthetic/plot.py
tests/test_plot.py

As raised in #149 there is a slight difference in how `'kde'` and `'fastkde'` treat the plot limits (`xlim`).
I believe this is down to a bug in `fastkde_plot_1d` (and `2d`?) which checks _twice_ whether the data reach up to the prior boundary (corresponding function is called `check_bounds`). This leads to (unwanted) extra 
**Subtle point to note regarding intended default behaviour for `'kde'` plots _(different from `'hist'` default)_:** 
* When the data spans the entire prior volume (e.g. uniform likelihood to uniform prior), the limits should be set to the prior boundaries. 
* When the data is contained in a much smaller volume than the prior volume (e.g. Gaussian likelihood to uniform prior), then the plotting limits should be reduced accordingly.  
(Feel free to comment/critique.) …

bugfix for xlim for fastkde plots

---

requirements.txt
setup.py
tests/test_gui.py

The tests in #152 and #153 were failing, but this was actually down to an API change in matplotlib 3.4 that affected the GUI. This provides a quick fix to the GUI tests to make them pass. However with some new deprecation warnings from matplotlib it looks like we will soon have to adapt the GUI section accordingly.

GUI tests quick fix due to matplotlib 3.4 API change

---

anesthetic/plot.py

This implements the suggestion from #140 to match the edgecolor from contourplots to the facecolor by default.
Fixes #140

change default edgecolor: match facecolor

---

anesthetic/plot.py

This addresses #156 which pointed out that `vmin` in 2d histograms needs to be set to zero in order for uniform distributions to appear uniform. 
Fixes #156

vmin=0 in 2d histograms

---

anesthetic/plot.py
tests/test_plot.py

This implements the `density` kwarg to 1d plots to allow for normalisation by area instead of setting the posterior maximum to one. Do we like this? Then I would go ahead with this.
I chose the kwarg `density` in line with matplotlib's `density` kwarg for `plt.hist` which already implements exactly that.
Example behaviour:
```python
import numpy as np
import matplotlib.pyplot as plt
from anesthetic import NestedSamples, MCMCSamples, make_1d_axes, make_2d_axes
from anesthetic.plot import kde_plot_1d, hist_plot_1d
params = ["x0", "x1", "x2"]
x0 = np.random.normal(loc=0, scale=1.0, size=2000)
x1 = np.random.normal(loc=1, scale=2.0, size=2000)
x2 = np.random.normal(loc=2, scale=0.5, size=2000)
fig, axes = plt.subplots(2, 2)
kde_plot_1d(axes[0, 0], x0)
kde_plot_1d(axes[0, 0], x1) …
```

optional normalisation by area instead of by maximum

---

README.rst
anesthetic/samples.py
tests/test_samples.py

This bug fixes adjusts the default behaviour. In general I have found that this error tends to occur due to floating point rounding errors at the end of the run, which can be safely discarded before recomputing the number of live points. This PR changes the behaviour to raising a RuntimeWarning with a message that indicates how many rows are discarded, and an encouragement for the user to inspect the chains files directly for anything that might be awry.
@sebhoof & @catherinewatkinson have also noted that this affects some of their pipelines -- any feedback for this potential fix would be much appreciated.
Fixes #141

Change in behaviour from RuntimeError to RuntimeWarning for invalid nested sampling runs

---

anesthetic/samples.py
tests/test_samples.py

As addressed in #165, when one uses an `MCMCSamples` or `NestedSamples` instance to create new derived parameters, the corresponding limits are not automatically updated. This PR calls `self._set_automatic_limits()` at the start of the generic `plot`, thus ensuring that the limits of any new derived parameters are updated before plotting them.
Fixes #165

auto update limits of derived parameters

---

.github/workflows/CI.yml
anesthetic/utils.py
anesthetic/weighted_pandas.py
requirements.txt
tests/test_weighted_pandas.py

The failing tests in #153, #162, #163, #167, and #168 appear to be a result of problems in pandas itself, introduced in pandas 1.3.0.
Setting pandas requirements to `pandas<1.3.0` to test this hypothesis.
EDIT: Confirmed, setting `pandas<1.3.0` let's tests pass (once conda CI got fixed).
---
The problem in the failing tests turns out, that pandas `quantile` is calling itself with the kwargs `axis`, `numeric_only` and `interpolation`. However anesthetic's inherited `WeightedDataFrame` overwrites that method without allowing for all these kwargs. In the self call this then results in a TypeError.
This is pandas `quantile` method calling itself:
```python
def quantile(
self,
q=0.5,
axis: Axis = 0,
numeric_only: bool = True,
interpolation: str = "linear",
):
"""
[...]
""" …
```

Upgrade to quantile function arising from pandas 1.3.0 internals change

---

anesthetic/samples.py
tests/test_samples.py
tests/wedding_cake.py

This PR adjusts so that `NestedSamples.live_points` 
- Returns equally weighted `MCMCSamples` (rather than posterior weighted `NestedSamples`
- changes the convention so that an integer argument now refers to the live point iteration before contour i is deleted, rather than after
Fixes #160

Equally weighted live points

---

anesthetic/plot.py
tests/test_plot.py

This PR addresses #164 and provides the method `axlines` that can be applied to the `axes` dataframe which adds vertical and horizontal lines to all subplots for a given parameter value. This is achieved by subclassing `pandas.Series` and `pandas.DataFrame` (we call the new objects `AxesSeries` and `AxesDataFrame` respectively) and then creating the new method `axlines` which broadcasts matplotlib's `axvline` and `axhline` across all axes.
Fixes #164

axlines method to highlight specific parameter values across all subplots

---

anesthetic/plot.py
tests/test_plot.py

For a description of the bug, see #174. This PR aims at fixing that bug.
Fixes #174

fix `axlines` and `axspans` for axes with `upper=False`

---

anesthetic/plot.py
tests/test_plot.py
tests/test_samples.py

This PR addresses the API change in [matplotlib version 3.5.0](https://matplotlib.org/3.5.0/api/prev_api_changes/api_changes_3.5.0.html#axes-children-are-no-longer-separated-by-type) that currently breaks our code/tests, as raised by Stefan in #183.
Fixes #183

adapt to breaking chanes in matplotlib API version 3.5.0

---

README.rst
anesthetic/samples.py

When dropping points associated with unordered likelihoods (which raises a
warning as of #159), since the pandas `reset_index` function has `drop=False`
by default, this has the unexpected behaviour of creating an extra `index`
column. This PR adjusts this by explicitly setting `drop=True` it does earlier
in the function

Fixing unexpected behaviour associated with reset_index

---

README.rst
anesthetic/samples.py
tests/test_samples.py

In the process of solving #182 with #186, I uncovered a somewhat nasty bug associated with a premature sort command in `NestedSamples.recompute`, present since #126. This affects arrays that are constructed or loaded which don't have sorted loglikelihood contours. The effect of the bug is to randomise the `logL_birth` contour. Whilst dead points are stored in loglikelihood order, live points are generally not. I believe that bug has remained hidden since 
1. in the most instances for a completed run with reasonable (i.e. default) termination criteria the effect of somewhat randomised live points shouldn't matter 
2. this doesn't affect polychord points due to the [line](https://github.com/williamjameshandley/anesthetic/blob/ad78c426be5b0b69a63314650f8cf3a8d1779437/anesthetic/read/polychord …

Fix for unsorted logL construction bug

---

anesthetic/utils.py
tests/test_samples.py

Add
```
x = np.array(x)
y = np.array(y)
```
to `triangular_sample_compression_2d` (already present in `sample_compression_1d`) as suggested by @williamjameshandley.
Fixes #189
` 153 passed, 3 xfailed, 1 xpassed, 16 warnings`

Fix #189, merge_samples_weighted breaking triangular_sample_compression_2d

---

anesthetic/samples.py
tests/test_samples.py

Currently `NestedSamples(data=...,logL=...,logL_birth=...)` assumes that `logL` and `logL_birth` are numpy arrays. It shouldn't.
This adds a test which shows this behaviour, and then fixes with a quick conversion.

Allow NestedSamples to take lists as well as numpy arrays as constructors

---

.github/workflows/CI.yml
tests/test_gui.py
tests/test_plot.py
tests/test_samples.py
tests/test_utils.py
tests/test_weighted_pandas.py

There has been a PEP update which means that our lint CI is now failing. This is a relatively straightforward change, which touches a lot of the tests, but otherwise does little, changing
`assert(...)` to `assert ...`

Updated for most recent PEP compliant assert statements

---

anesthetic/utils.py

Single line fix using `c=c/c[-1]` rather than `c/=c[-1]` which keeps creeping up in PRs and I want it fixed _now_...
Would be nice to push this through.

Quick fix `c/=c[-1]` to `c=c/c[-1]`

---

anesthetic/boundary.py
anesthetic/convert.py
anesthetic/plot.py
anesthetic/read/chainreader.py
anesthetic/read/cobayamcmcreader.py
anesthetic/read/getdistreader.py
anesthetic/read/montepythonreader.py
anesthetic/samples.py
tests/test_plot.py
tests/test_reader.py
tests/test_samples.py
tests/test_utils.py

This PR addresses #200 and 
1) removes the `limits` attribute of `Samples`, `MCMCSamples`, and `NestedSamples`, and
2) removes the `xmin` and `xmax` (and `ymin` and `ymax` kwargs passed to the plotting functions.
Fixes #200

remove `limits` attribute and `xmin` and `xmax` kwargs

---

anesthetic/samples.py
tests/test_samples.py

#207 introduced a bug whereby `samples.plot_2d(...)` no longer has the correct tex in all of the labels. This arises because `samples.plot(...)` defaults to using the column label, which can overwrite the labels set up by `make_2d_axes`. This fixes that by passing `xlabel` explicitly through `samples.plot` in `samples.plot_2d(...)`

Issue with plot labels

---

anesthetic/convert.py
anesthetic/plotting/_matplotlib/core.py
anesthetic/samples.py
anesthetic/utils.py
anesthetic/weighted_pandas.py
tests/test_convert.py
tests/test_reader.py
tests/test_samples.py
tests/test_weighted_pandas.py
tests/wedding_cake.py

This provides a few simultaneous upgrades to WeightedPandas, which were sparked by some of the indexing considerations in #194. These are
1. `WeightedDataFrame` and `WeightedSeries` always have a weights column in their `MultiIndex`. If no weights are passed, the column is filled with 1's (integers).
2. More complicated `MultiIndex`es are now possible (previously it was assumed there would be only one other 'iteration' column).
3. The 'other' column is now no longer called `'#'`, but will retain the name of the previous index/indices (if present at all).
The above changes make the code more robust and extensible, particularly when it comes to extracting/dropping weights (we can assume that `df.index.get_level_values('weights')` and `df.index.droplevel('weights')` will always work), but …

WeightedPandas index improvements

---

scripts/anesthetic

Small changes to match new reading style for the included command line script to launch the gui
Fixes #227

update gui script

---

.readthedocs.yml

This increments to 3.8 in the .readthedocs.yml file, which should hopefully fix the read the docs builds

Updated .readthedocs.yml to be python 3.8

---

.github/workflows/CI.yml

macos and windows workflows are stuck much longer in the GitHub action queues and we might not need a quite as extensive coverage of all options. 
This PR reduces the workflow matrix such that macos and windows are only run with python version 3.10.

reduce CI workflow matrices

---

anesthetic/read/cobaya.py
anesthetic/read/getdist.py
anesthetic/read/multinest.py
anesthetic/read/polychord.py

I noticed that `labels` isn't passed along in the same way as `columns` when reading chains.

pass labels argument through when reading chains

---

.github/workflows/CI.yml
tests/test_plot.py
tests/test_reader.py
tests/test_samples.py
tests/test_weighted_pandas.py

This PR achieve two things
1) It streamlines the CI so that we test [osx,windows]x[pip,conda]x[3.10] + [linux]x[pip,conda]x[3.8,3.9,3.10]. This reduces build times since osx and windows are reduced by a factor of 3, and expands the (much faster) linux builds to include 3.9.
2) We aim to remove all side effects from pandas plotting functions
(2) is an insidious bug which has been affecting all current PRs non-deterministically. Tests pass on local machines, but when lifted to the CI servers sometimes break in certain functions. The hypothesis is that pandas plotting is very inconsistent, for example `.plot.box()` creates a new axis, whilst `.boxplot()` uses the 'current axis' with e.g. `plt.gca()`. It is the latter functions which cause the problem by potentially getting a current axis …

Fix to non-deterministic behaviour by removing long-range side effects

---

tests/test_weighted_pandas.py

Replacing `df.groupby('split').boxplot()` with `df.groupby('split').plot.box()` in `tests/test_weighted_pandas.py::test_BoxPlot()` seems to avoid the problem where the plots in the later `test_AreaPlot()` non-deterministically believe their axes to be shared, which prevents them from setting the lower y limit to 0. The original tests only fail when this happens to only one of the two.
Seeing as this is occurring for unmodified `pandas.DataFrame`s, I don't think this is something we can fix easily in `anesthetic`

replace `.boxplot()`with `.plot.box()`

---

docs/source/anesthetic.rst

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
Fixes # (issue)

remove show-inheritance from anesthetic.core to see if this fixes docs
